<?php
/*
  Generated by http://wpsettingsapi.jeroensormani.com/
*/

function tamhsc_add_admin_menu(  ) {
  add_submenu_page( 'options-general.php', 'TAMHSC Customization', 'TAMHSC Customization', 'manage_options', 'tamhsc_customizations', 'tamhsc_customizations_options_page' );
}
add_action( 'admin_menu', 'tamhsc_add_admin_menu' );


function tamhsc_settings_init(  ) {
  register_setting( 'pluginPage', 'tamhsc_settings' );

  add_settings_section(
    'tamhsc_pluginPage_section',
    __( 'Options', 'wordpress' ),
    'tamhsc_settings_section_callback',
    'pluginPage'
  );

  add_settings_field(
    'tamhsc_checkbox_field_0',
    __( 'Allow Editors to modify widgets and menus?', 'wordpress' ),
    'tamhsc_checkbox_field_0_render',
    'pluginPage',
    'tamhsc_pluginPage_section'
  );

  /*
  add_settings_field(
    'tamhsc_checkbox_field_1',
    __( 'Settings field description', 'wordpress' ),
    'tamhsc_checkbox_field_1_render',
    'pluginPage',
    'tamhsc_pluginPage_section'
  );
  */
}
add_action( 'admin_init', 'tamhsc_settings_init' );

function tamhsc_checkbox_field_0_render(  ) {
  $options = get_option( 'tamhsc_settings' );
  if (empty($options)){
    $options['tamhsc_checkbox_field_0'] = 0;
  }
  ?>
  <input type='checkbox' name='tamhsc_settings[tamhsc_checkbox_field_0]' <?php checked( $options['tamhsc_checkbox_field_0'], 1 ); ?> value='1'>
  <?php
}

/*
function tamhsc_checkbox_field_1_render(  ) {

  $options = get_option( 'tamhsc_settings' );
  ?>
  <input type='checkbox' name='tamhsc_settings[tamhsc_checkbox_field_1]' <?php checked( $options['tamhsc_checkbox_field_1'], 1 ); ?> value='1'>
  <?php

}
*/


function tamhsc_settings_section_callback(  ) {

}


function tamhsc_customizations_options_page(  ) {
  ?>
  <div class="wrap">
    <form action='options.php' method='post'>

      <h2>TAMHSC Customizations</h2>

      <?php
        settings_fields( 'pluginPage' );
        do_settings_sections( 'pluginPage' );
        submit_button();
      ?>

    </form>
  </div>
  <?php
}

?>
